steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/online-selfbot:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/online-selfbot:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'online-selfbot'
      - '--image=gcr.io/$PROJECT_ID/online-selfbot:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=2048Mi'
      - '--allow-unauthenticated'
      - '--set-secrets=TOKENS=tokens:latest'
images:
  - 'gcr.io/$PROJECT_ID/online-selfbot:$COMMIT_SHA'
logsBucket: 'gs://online-selfbot-buckets/logs'